name: Expressions
on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        required      : true
        default       : false
        type          : boolean
        description   : Habilitar modo debug
      fail:
        required      : true
        default       : false
        type          : boolean
        description   : Habilitar fail

env:
  WORKFLOW_VAR        : This is a workflow-level variable
  OVERWRITTEN         : Defalut workflow value

jobs:
  debug-check:
    runs-on           :  ubuntu-latest
    env:
      job_var         : This is a job-level variable
      overwritten     : Overwritten at job level
    steps:
      
      - name          : Print Debug Info
        if            : inputs.debug
        run           : |
          echo "Triggered by: ${{ github.event_name }}" 
          echo "Branch: ${{ github.ref }}" 
          echo "Commit SHA: ${{ github.sha }}" 
          echo "Runner OS: ${{ runner.os }}"

      - name          : Triggered from Main
        if            : inputs.debug && github.ref_name == 'main'
        run           : echo "Triggered from main branch!"
